pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sendNotification('started', 'team@lmc.io')
                // git branch: 'main',
                    // url: 'https://gitlab.consulting.redhat.com/skywalker/rhu/DO400-apps.git'
            }
        }
        stage('Test') {
            steps {
                dir('simple-calculator') {
                    withMaven(globalMavenSettingsConfig: '2bc73d01-df9a-4505-9dc3-304673486172') {
                        sh 'mvn clean test'
                    }
                }
            }
        }
        stage('Check Style') {
            steps {
                dir('simple-calculator') {
                    withMaven(globalMavenSettingsConfig: '2bc73d01-df9a-4505-9dc3-304673486172') {
                        sh 'mvn clean checkstyle:check'
                    }
                }
            }
        } 
    }
    post {
        failure {
            sendFailureAlert('team@lmc.io')
        }
        always {
            sendNotification('finished', 'team@lmc.io')
        }
    }
}
void sendNotification(String action, String email) {
    emailext to: "${email}",
        subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}
void sendFailureAlert(String email) {
    emailext to: "${email}",
        subject: "Pipeline failed: ${currentBuild.fullDisplayName}",
        body: "The following pipeline failed: ${env.BUILD_URL}"
}
